### ISSUE TITLE
Difficulty range issue when difficulty_mode < difficulty_rating

### ISSUE THREAD

**Issue by RePod** [Cynichill/DivaAPworld#20]
Specifically when there's no rating overlap:
```YAML
  song_difficulty_mode: easy
  song_difficulty_rating: hard
# easy   1 - 4.5
# normal   3 - 6.5
# hard       4 - 8
# ex           6 - 10
# exex         6 - 10
```
Despite Easy and Hard having overlapping ranges, no base+DLC songs show up in *both* resulting in 0 `available_song_keys`.
For future reference, some officials may not have every diff either. `Jaded`, `Far Away` and `Packaged` lack Normals, but are from the H4-4.5 range.

This is caught "earlier" when selecting the goal song:
```Py
 File "R:\Archipelago\Client\lib\worlds\megamix\__init__.py", line 90, in generate_early
    chosen_song_index = random.randrange(0, len(available_song_keys))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "random.py", line 319, in randrange
ValueError: empty range in randrange(0, 0)
```
https://github.com/Cynichill/DivaAPworld/blob/4a4868ef34b751143110209b6e5a002512fa21e1/__init__.py#L87-L91

----

`get_available_difficulties()` currently only handles `Any` and `Manual`:

https://github.com/Cynichill/DivaAPworld/blob/dd8eeab09785e51602b1fa90486d16f9895c8c91/Options.py#L46-L64

https://github.com/Cynichill/DivaAPworld/blob/4a4868ef34b751143110209b6e5a002512fa21e1/__init__.py#L306-L319

See also #19
