### ISSUE TITLE
Feature: include_songs percentage

### ISSUE THREAD

**Issue by RePod** [Cynichill/DivaAPworld#42]
Currently `include_songs` is non-negotiable and can either lower or prevent the appearance of non-included songs as it grows.
For example, 30 `include_songs` in a 30 song seed (3 starting, 26 additional, 1 goal) would cover the whole seed.

A percentage could, deterministically, pick a smaller set out of `include_songs` leaving the rest open for non-included and included that weren't picked.
The idea being that either directly or through use of triggers, playlists can be built that far exceed the seed's song count without completely taking it over.

A trigger example would be:
```YAML
Hatsune Miku Project Diva Mega Mix+:
  include_songs: # Either empty or a few pre-defined
    - Deep Sea City Underground [234]
  include_songs_percentage: 50 # Range 0-100, default 100
  add_deco: true # Custom property for the trigger

triggers:
  - option_category: Hatsune Miku Project Diva Mega Mix+
    option_name: add_deco
    option_result: true
    options:
      Hatsune Miku Project Diva Mega Mix+:
        +include_songs: # The + adds on to the existing value
          - Ghost Rule [266]
```
A percentage option of `50` would *intentionally* include one or the other in the example, but not both.
Included songs that weren't selected would stay in the available pool.

There's also the alternative application of "maximum percentage of seed's song pool allocated to included songs". A small difference but may scale better.
